---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r load libraries}
library(ggplot2)
library(tidyverse)
```

```{r}
set.seed(500)
#how many times to run
sims <- 500
#what sort of bear purchase scnearios do we want to test for?
sample <- seq(from=175,to=325,by=5)
#turn our sample vector of (A,B,C) to (A,A,A,B,B,B,C,C,C) sims number of times
buy <- rep(sample,each=sims)

#create our demand scenarios. sample from a random distribution. round down.
demand <- floor(rnorm(sims,mean=192.0,sd=58.13))
#apply our demand across the entire length of scenario
demand <- rep(demand,times=length(sample))

#can't sell what we don't have. can't have negative unsold
sold <- ifelse(demand>=buy,buy,demand)
unsold <- ifelse(buy==sold,0,buy-sold)

#profit calculation
revenue <- sold*12.95+unsold*5.43*.8
cost <- buy*5.43
expProfit <- revenue-cost

#wrap it together
results <- data.frame(buy,demand,sold,unsold,revenue,cost,expProfit)

#QC the data
head(results)
```

```{r}
#QC continued
tail(results)
```

```{r}
#plot each scenario histograms
ggplot(results,aes(x=expProfit))+geom_histogram()+facet_wrap(~buy)
```

```{r}
#aggregate results
test <- results %>%
  group_by(buy) %>%
  summarize(meanProfits=mean(expProfit),
            sdProfits=sd(expProfit),
            stockout=sum(unsold==0)/sims)

#look at it
test
```



```{r}
#plot profits
ggplot(test,aes(x=buy,y=meanProfits))+geom_point()
```

```{r}
#plot stockout rate. should fit N(mean=192,sd=58.13)
ggplot(test,aes(x=buy,y=stockout))+geom_point()
```
